spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

camunda.bpm.admin-user:
  id: demo
  password: demo

server:
  port: 8081